### ISSUE TITLE
 APR-4000(mk4turboprop-125-1) reverse thrust not working

### ISSUE THREAD

**Issue by AkanoLoki** [ChrisAdderley/MkIVSystem#19]
path:Parts\Engine\mk4turboprop-125-1
Thrust reversing is not working: engine still produces normal thrust after toggled. Consider revising alternateThrustTransform axes.

**Comment by ChrisAdderley** [comment]
This actually doesn't seem to work for either propeller, and the transforms are completely fine

**Comment by ChrisAdderley** [comment]
Fixed in 2.3.0
