### ISSUE TITLE
mk4multimodal-125-1 has bad attachnode size

### ISSUE THREAD

**Issue by linuxgurugamer** [ChrisAdderley/MkIVSystem#27]
This came up in The Janitor's Closet, which looks at all the attachnode sizes.
Apparently, one of the attachnode sizes on this part is set to -1, which caused an exception.  I've fixed it in my mod, but the value just seems wrong to me

**Comment by linuxgurugamer** [comment]
A user on tthe forum, Jiraiyah, came up with the following MM patch to fix:

@PART[mk4multimodal-125-1]:Final
{
    %node_stack_bottom = 0.0,-0.8541491, 0.0, 0.0, 1.0, 0.0, 1
}

**Comment by ChrisAdderley** [comment]
Resolved in upcoming release.
