### ISSUE TITLE
Configs for mk4turbojet-25-1 and mk4turbofan-25-2 are nearly identical

### ISSUE THREAD

**Issue by grylliade** [ChrisAdderley/MkIVSystem#38]
As far as I can tell, the ModuleEnginesFX for these two engines is identical, as are their masses and costs. It doesn't seem like this is intentional, given the differences in their descriptions.

**Comment by ChrisAdderley** [comment]
Perhaps you could consider some statistical changes that would place the engines in the same place as their descriptions and propose them?

**Comment by grylliade** [comment]
Certainly! I'll do my best—I just figured it was an oversight right off the bat, and that you already had numbers that just weren't in the cfg.

**Comment by ChrisAdderley** [comment]
Did you ever get a chance to look at this?
