### ISSUE TITLE
Thrust/etc not computable for BROADSWORD/other engines BUG

### ISSUE THREAD

**Issue by arekbulski** [ChrisAdderley/MkIVSystem#43]
As discussed on the forum:

> On 14.11.2017 at 4:12 AM, docthaspok said:
>
> Somewhat of a workaround, used TextPad to compared the *.cfg files for the engines vs. version 2.3.6 *.cfg files, and commented the two lines with primaryEngineModeDisplayName  and  secondaryEngineModeDisplayName. After that Kerbal engineer showed Delta V, TWR and thrust, so far nothing has broken.
> 
> Yes that's the reason, I just haven't got around to actually releasing the fix... Bug in squad s stuff, doesn't work as documented.
>

**Comment by ChrisAdderley** [comment]
Indeed. Already fixed in dev like I mentioned.

**Comment by arekbulski** [comment]
Then please make a release. :)
