### ISSUE TITLE
Mk4 new inline parts

### ISSUE THREAD

**Issue by arekbulski** [ChrisAdderley/MkIVSystem#44]
I would like to request adding parts for:

- mk4 decoupler (there is mk2 decoupler)
- mk4 inline RCS/SAS (there is OPT J part)
- mk4 inline ramp (like cargo ramp but not as tail, so cargo can be unloaded by ramp but engine mount still be attached onto it)

**Comment by ChrisAdderley** [comment]
I have no plans to make more parts for this mod, unfortunately.

**Comment by arekbulski** [comment]
If I modeled those parts myself (I had used Blender but am not a professional in that respect), would you consider adding those parts to the mod?

**Comment by ChrisAdderley** [comment]
Probably not, but there's nothing stopping you from releasing it as an addon.
